# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=50)),
                ('horario_inicio', models.CharField(max_length=50)),
                ('horario_termino', models.CharField(max_length=50)),
                ('cantidad_usuarios', models.CharField(max_length=50)),
            ],
        ),
    ]
