# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salas',
            name='fecha_reserva',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
