# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reservas', '0002_auto_20170223_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
