# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0003_salas_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salas',
            new_name='Sala',
        ),
    ]
